# Generated by Django 5.1.1 on 2024-09-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_date',
            new_name='date',
        ),
    ]
